### ISSUE TITLE
how to produce estimated coefficient surfaces of GWR

### ISSUE THREAD

**Issue by sliencetree** [jhagenauer/gwann#11]
hello，When I finish reading this article, I want to know how to produce estimated coefficient surfaces of GWR

**Comment by jhagenauer** [comment]
I think you mean GWANN and not GWR? When you run you optain an Objekt which contains a matrices of connection weights. Plotting the last matrix gives you a surface of connection weights. For real-world use-cases this is of no use, though, because interpretation of the surfaces is not really possible.

**Comment by sliencetree** [comment]
> I think you mean GWANN and not GWR? When you run you optain an Objekt which contains a matrices of connection weights. Plotting the last matrix gives you a surface of connection weights. For real-world use-cases this is of no use, though, because interpretation of the surfaces is not really possible.
You are right and thanks for your reply, it cleared up my confusion

**Comment by sliencetree** [comment]
> I think you mean GWANN and not GWR? When you run you optain an Objekt which contains a matrices of connection weights. Plotting the last matrix gives you a surface of connection weights. For real-world use-cases this is of no use, though, because interpretation of the surfaces is not really possible.

You are right and thanks for your reply, it cleared up my confusion

**Comment by jhagenauer** [comment]
Closed.
